name = "Skye"
license = "MIT"
licenselink = "https://github.com/pauby/hugo-theme-skye/blob/master/LICENSE.md"
description = "A dark theme with blue accents for Hugo. Provides multiple configuration options and overrides."
homepage = "https://github.com/pauby/hugo-theme-skye"
tags = ["Blog", "Dark", "No JavaScript", "Responsive", "Syntax Highlighting", "Writing"]
min_version = 0.20

[author]
  name = "Paul Broadwith"
  homepage = "https://pauby.com"
