baseurl = "http://hugo.spf13.com/"
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
canonifyurls = true
paginate = 3
theme = "BluestNight"
PygmentsCodeFences = true
PygmentsStyle = "monokai"

[outputs]
    home = ["HTML", "CSS"]

[Params]
    tagline = "An example tagline for my Hugo site" # Subtitle of your site
    description = "Here is a description of my site that will appear in search engine results - W00t!" # Description of your site
    authorbox = true
    author = "Some Guy" # Name must exist in an entry in /data/members
    postNavigation = false

[Params.widgets]
    articleRecent = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tagCount = true # Enable tag count on tag widgets

[Params.color]
    backgroundPage = "#000000"
    backgroundWindow = "#050505"
    backgroundAlt = "#252525"
    textDefault = "#e2e2e2"
    textAlt = "#e2e2e2"
    accent = "#2c8cef"
    textHeader = "#e2e2e2"
